#!/usr/bin/python3
from matplotlib.pyplot import imshow,show,subplots,subplot,figure
from cv2 import cvtColor,imread,COLOR_BGR2RGB,COLOR_RGB2HSV,inRange
from numpy import array
a=imread('imagen.jpg')
a=cvtColor(a,COLOR_BGR2RGB)
#objeto=imshow(a)
#show(objeto)
r=a[:,:,0]
g=a[:,:,1]
b=a[:,:,2]
#figure1,(fig1,fig2,fig3)=subplots(1,3,figsize=(20,10))

#fig1.imshow(r, cmap='gray')
#fig2.imshow(g, cmap='gray')
#fig3.imshow(b, cmap='gray')
#figure()
#imshow(a)
#show()
b=cvtColor(a,COLOR_RGB2HSV)
h=b[:,:,0]
s=b[:,:,1]
v=b[:,:,2]
#figure1,(fig1,fig2,fig3)=subplots(1,3,figsize=(20,10))
#fig1.imshow(h, cmap='gray')
#fig2.imshow(s, cmap='gray')
#fig3.imshow(v, cmap='gray')
#show()
hsvlow=array([46,110,120])
hsvhigh=array([127,255,200])
mascara=inRange(b,hsvlow,hsvhigh)
#imshow(mascara)
#show()
a[mascara!=0]=[255,0,0]
imshow(a)
show()
